# Generated by Django 5.1.7 on 2025-03-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
